app: goFrame
port: 10110
env: loc
ping: app
logLevel: DEBUG
consul:
  host: 58.246.173.179
  port: 8500

mongo:
  host: dev-api.neoclub.cn
  port: 27017
  user:
  pwd:

redis:
  host: dev-api.neoclub.cn
  port: 6379
  pwd: