env: loc
logLevel: DEBUG
consul:
  host: 58.246.173.179
  port: 8500

mongo:
#  host: dev-api.neoclub.cn
  host: localhost
  port: 27017

redis:
#  host: dev-api.neoclub.cn
  host: localhost
  port: 6379
  pwd:
